### PR TITLE
New AD logo

### PR DESCRIPTION
**Pull request by globalavocado**
added sponsor logo & changed spacing to accomodate

### CODE REVIEW

**Comment by sebastianovide** [comment]
@globalavocado  have you decide to break free from photos ?

**Comment by globalavocado** [comment]
@sebastianovide I can put it in photos instead.

**Comment by sebastianovide** [comment]
@globalavocado wait. As before going into photos it should pass our UX guardian @RBGV and it should be customizable (REN logo is hardcoded in your PR). We are probably discontinuing photos so you may break free...

**Comment by sebastianovide** [comment]
hi @globalavocado . I've tried to add also @munroTom as reviewer by Githhub doesn't allow me. Can you try ?

**Comment by globalavocado** [comment]
@sebastianovide hmm, I can't add Tom either...

**Comment by globalavocado** [comment]
I added more padding & renamed the image to the more generic 'sponsor-logo.png' and moved it to public/custom as the sponsor may change over time.

**Comment by sebastianovide** [comment]
merged in https://github.com/Geovation/plastic-patrol/pull/228

**Pull request closed without merging**
