### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by munroTom**

### CODE REVIEW

**Comment by sebastianovide** [comment]
29 files changed

**Comment by munroTom** [comment]
Might be an issue with the diffs, the majority of files changed should now be in due to https://github.com/Geovation/plastic-patrol/pull/251 which also has the commit 59f380343d165877466ed2acfe5e19f5c4523928 where I moved PhotoPage into the Pages directory, I'll take a look next time I get the chance

**Comment by sebastianovide** [comment]
@munroTom perhaps it contains changes that were part of the previous PR ??? (see the conflicts)

**Comment by munroTom** [comment]
@sebastianovide should be good to merge now

**Comment by sebastianovide** [comment]
nice

**Pull request merged**
